
/**
 * Generated by Database Modeler Lite
 * https://play.google.com/store/apps/details?id=adrian.adbm
 * 
 * Created: 5 de jun. de 2024
*/


/*
DROP TABLE IF EXISTS `funcionário`;

*/


CREATE DATABASE oranges;
USE oranges;

CREATE TABLE `funcionário` (
    `id` INT (10) NOT NULL AUTO_INCREMENT,
    `cpf` VARCHAR (100) NOT NULL,
    `nome` VARCHAR (100) NOT NULL,
    `idade` INT (10) NOT NULL,
    `cargo` VARCHAR (100) NOT NULL,
    `setor` VARCHAR (100) NOT NULL,
    `dataCriacao` VARCHAR (100) NOT NULL,
    `dataAtualizacao` VARCHAR (100) NOT NULL,
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8;





